// <auto-generated />
using System;
using EVrtic.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EVrtic.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260511211310_AddIdentityTables")]
    partial class AddIdentityTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EVrtic.Models.AlergijaDjeteta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DijeteId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DijeteId");

                    b.ToTable("AlergijaDjeteta", (string)null);
                });

            modelBuilder.Entity("EVrtic.Models.BolestDjeteta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DijeteId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DijeteId");

                    b.ToTable("BolestDjeteta", (string)null);
                });

            modelBuilder.Entity("EVrtic.Models.Dijete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivno")
                        .HasColumnType("bit");

                    b.Property<string>("DodatnaNapomena")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("GrupaId")
                        .HasColumnType("int");

                    b.Property<string>("IdentifikacioniKod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ImePrezime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RoditeljId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrupaId");

                    b.HasIndex("IdentifikacioniKod")
                        .IsUnique();

                    b.HasIndex("RoditeljId");

                    b.ToTable("Dijete", (string)null);
                });

            modelBuilder.Entity("EVrtic.Models.DnevniIzvjestaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<int>("DijeteId")
                        .HasColumnType("int");

                    b.Property<string>("NapomenaAktivnosti")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Obrok")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SpavanjeMinuta")
                        .HasColumnType("int");

                    b.Property<int>("StatusObroka")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("VrijemeDolaska")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("VrijemeOdlaska")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("DijeteId");

                    b.ToTable("DnevniIzvjestaj", (string)null);
                });

            modelBuilder.Entity("EVrtic.Models.DnevniQRCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivan")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DatumVazenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("VrijednostKoda")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("VrijemeIsteka")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DnevniQRCode", (string)null);
                });

            modelBuilder.Entity("EVrtic.Models.EvidencijaDolaskaOdlaska", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DijeteId")
                        .HasColumnType("int");

                    b.Property<int?>("DnevniQRCodeId")
                        .HasColumnType("int");

                    b.Property<bool>("KodDjetetaIspravan")
                        .HasColumnType("bit");

                    b.Property<int>("StatusEvidencije")
                        .HasColumnType("int");

                    b.Property<int>("TipDogadjaja")
                        .HasColumnType("int");

                    b.Property<string>("UneseniKodDjeteta")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("ValidanQRKod")
                        .HasColumnType("bit");

                    b.Property<DateTime>("VrijemeDogadjaja")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DijeteId");

                    b.HasIndex("DnevniQRCodeId");

                    b.ToTable("EvidencijaDolaskaOdlaska", (string)null);
                });

            modelBuilder.Entity("EVrtic.Models.Grupa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImeGrupe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OdgajateljId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OdgajateljId");

                    b.ToTable("Grupa", (string)null);
                });

            modelBuilder.Entity("EVrtic.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ImePrezime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StatusNaloga")
                        .HasColumnType("int");

                    b.Property<int>("Uloga")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Korisnik", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EVrtic.Models.Obavijest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumSlanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("KanalSlanja")
                        .HasColumnType("int");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("OdgajateljId")
                        .HasColumnType("int");

                    b.Property<int>("RoditeljId")
                        .HasColumnType("int");

                    b.Property<string>("Sadrzaj")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("StatusObavijesti")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OdgajateljId");

                    b.HasIndex("RoditeljId");

                    b.ToTable("Obavijest", (string)null);
                });

            modelBuilder.Entity("EVrtic.Models.SazetakAktivnosti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgregiranoSpavanjeMinuta")
                        .HasColumnType("int");

                    b.Property<int>("BrojDolazaka")
                        .HasColumnType("int");

                    b.Property<int>("BrojObroka")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumGenerisanja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumKraja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumPocetka")
                        .HasColumnType("datetime2");

                    b.Property<int>("DijeteId")
                        .HasColumnType("int");

                    b.Property<string>("OsnovneNapomene")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("TipSazetka")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DijeteId");

                    b.ToTable("SazetakAktivnosti", (string)null);
                });

            modelBuilder.Entity("EVrtic.Models.Administrator", b =>
                {
                    b.HasBaseType("EVrtic.Models.Korisnik");

                    b.ToTable("Administrator", (string)null);
                });

            modelBuilder.Entity("EVrtic.Models.Odgajatelj", b =>
                {
                    b.HasBaseType("EVrtic.Models.Korisnik");

                    b.ToTable("Odgajatelj", (string)null);
                });

            modelBuilder.Entity("EVrtic.Models.Roditelj", b =>
                {
                    b.HasBaseType("EVrtic.Models.Korisnik");

                    b.ToTable("Roditelj", (string)null);
                });

            modelBuilder.Entity("EVrtic.Models.AlergijaDjeteta", b =>
                {
                    b.HasOne("EVrtic.Models.Dijete", "Dijete")
                        .WithMany("Alergije")
                        .HasForeignKey("DijeteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dijete");
                });

            modelBuilder.Entity("EVrtic.Models.BolestDjeteta", b =>
                {
                    b.HasOne("EVrtic.Models.Dijete", "Dijete")
                        .WithMany("Bolesti")
                        .HasForeignKey("DijeteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dijete");
                });

            modelBuilder.Entity("EVrtic.Models.Dijete", b =>
                {
                    b.HasOne("EVrtic.Models.Grupa", "Grupa")
                        .WithMany("Djeca")
                        .HasForeignKey("GrupaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EVrtic.Models.Roditelj", "Roditelj")
                        .WithMany("Djeca")
                        .HasForeignKey("RoditeljId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Grupa");

                    b.Navigation("Roditelj");
                });

            modelBuilder.Entity("EVrtic.Models.DnevniIzvjestaj", b =>
                {
                    b.HasOne("EVrtic.Models.Dijete", "Dijete")
                        .WithMany("DnevniIzvjestaji")
                        .HasForeignKey("DijeteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dijete");
                });

            modelBuilder.Entity("EVrtic.Models.EvidencijaDolaskaOdlaska", b =>
                {
                    b.HasOne("EVrtic.Models.Dijete", "Dijete")
                        .WithMany("EvidencijeDolaskaOdlaska")
                        .HasForeignKey("DijeteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EVrtic.Models.DnevniQRCode", "DnevniQRCode")
                        .WithMany("Evidencije")
                        .HasForeignKey("DnevniQRCodeId");

                    b.Navigation("Dijete");

                    b.Navigation("DnevniQRCode");
                });

            modelBuilder.Entity("EVrtic.Models.Grupa", b =>
                {
                    b.HasOne("EVrtic.Models.Odgajatelj", "Odgajatelj")
                        .WithMany("Grupe")
                        .HasForeignKey("OdgajateljId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Odgajatelj");
                });

            modelBuilder.Entity("EVrtic.Models.Obavijest", b =>
                {
                    b.HasOne("EVrtic.Models.Odgajatelj", "Odgajatelj")
                        .WithMany()
                        .HasForeignKey("OdgajateljId");

                    b.HasOne("EVrtic.Models.Roditelj", "Roditelj")
                        .WithMany()
                        .HasForeignKey("RoditeljId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Odgajatelj");

                    b.Navigation("Roditelj");
                });

            modelBuilder.Entity("EVrtic.Models.SazetakAktivnosti", b =>
                {
                    b.HasOne("EVrtic.Models.Dijete", "Dijete")
                        .WithMany("SazeciAktivnosti")
                        .HasForeignKey("DijeteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dijete");
                });

            modelBuilder.Entity("EVrtic.Models.Administrator", b =>
                {
                    b.HasOne("EVrtic.Models.Korisnik", null)
                        .WithOne()
                        .HasForeignKey("EVrtic.Models.Administrator", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EVrtic.Models.Odgajatelj", b =>
                {
                    b.HasOne("EVrtic.Models.Korisnik", null)
                        .WithOne()
                        .HasForeignKey("EVrtic.Models.Odgajatelj", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EVrtic.Models.Roditelj", b =>
                {
                    b.HasOne("EVrtic.Models.Korisnik", null)
                        .WithOne()
                        .HasForeignKey("EVrtic.Models.Roditelj", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EVrtic.Models.Dijete", b =>
                {
                    b.Navigation("Alergije");

                    b.Navigation("Bolesti");

                    b.Navigation("DnevniIzvjestaji");

                    b.Navigation("EvidencijeDolaskaOdlaska");

                    b.Navigation("SazeciAktivnosti");
                });

            modelBuilder.Entity("EVrtic.Models.DnevniQRCode", b =>
                {
                    b.Navigation("Evidencije");
                });

            modelBuilder.Entity("EVrtic.Models.Grupa", b =>
                {
                    b.Navigation("Djeca");
                });

            modelBuilder.Entity("EVrtic.Models.Odgajatelj", b =>
                {
                    b.Navigation("Grupe");
                });

            modelBuilder.Entity("EVrtic.Models.Roditelj", b =>
                {
                    b.Navigation("Djeca");
                });
#pragma warning restore 612, 618
        }
    }
}
